[project]
name = ""
description = ""
version = "1.0.0"
license = "LICENSE"

[project.urls]
Repository = ""
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = ""
DisplayName = "ComfyUI-AIT"
Icon = ""
